### ISSUE TITLE
 - ] aws : NOT INSTALLED

### ISSUE THREAD

**Issue by K0uR0sH3R** [noolep/AWCREC#1]
what should i do for this error ??  - ] aws : NOT INSTALLED

**Comment by noolep** [comment]
You must install awscli, you can install awscli from pip [ python package management, so if you if you don't have python installed you need to install it first ]

$ pip install awscli

Or more information about install awscli you can read this documents : https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
